import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ReduxProvider from "@/redux/ReduxProvider";

const nunitoSans = Nunito_Sans({
  weight: ["300", "600", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Where in the world",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} antialiased dark:bg-colorVeryDarkBlue2 bg-colorVeryLightGray`}>
        <ReduxProvider>
          <Navbar />
          <div className="md:px-32">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
